'''#HOLIDAY HOMEWORK
#1
#to read a string and print no.of:
#-capital letters
#-small letters
#-special symbols
#-words
st=input('Enter a sentence: ')
c=0
s=0
ss=0
w=len(st.split())
n=0
for i in st:
    if i.isupper():
        c+=1
    elif i.islower():
        s+=1
    elif i.isdigit() or i.isspace():
        n=0
    else:
        ss+=1
print('No. of capital letters: ',c)
print('No. of small letters: ',s)
print('No. of special symbols: ',ss)
print('No. of words: ',w)

#2
#to print a string after replacing its capital and small letters
st=input('Enter a string :')
st1=''
for i in st:
    if i.isupper():
        st1+=i.lower()
    else:
        st1+=i.upper()
print('The New String: ',st1)

#3
#create a dic to count the freq from a list
l=[]
n=int(input('Enter the limit: '))
for i in range(n):
    no=int(input('Enter the element: '))
    l.append(no)
print(l)
d={}
for i in l:
    if i in d:
        d[i]+=1
    else:
        d[i]=1
print(d)

#4
#menu driven program
d={}
n=int(input('Enter the limit: '))
for i in range(n):
    cou=input('Enter the name of the country: ')
    cap=input('Enter the capial of the country: ')
    d[cou]=cap
print(d)
print('1.Enter the name of the country')
print('2.Enter the capital of the country')
while True:
    ch=int(input('Enter the choice: '))
    if ch==1:
        c1=input('Enter the name of the country to know its capital: ')
        if c1 in d:
            print(d[c1])
        else:
            print('Country not found in the dictionary')
    elif ch==2:
        c2=input('Enter the name of the capital to know its country: ')
        for i in d:
            if d[i]==c2:
                print(i)
            else:
                pass
        if d[i]!=c2:
            print('Capital not found in the dictionary')
    else:
        break
    
#5
#to shift elements of the list
l=[]
n=int(input('Enter the limit: '))
for i in range(n):
    no=int(input('Enter the element: '))
    l.append(no)
print(l)
t=l[n-1]
for i in range(n-1,0,-1):
    l[i]=l[i-1]
l[0]=t
print('The New List: ',l)

#6
#to display all the prime no. in the range 1 to N
def prime(N):
    for no in range(2,N+1):
        if no>1:
            for i in range(2,no):
                if no%i==0:
                    break
            else:
                print(no,end=',')
N=int(input('Enter the range: '))
prime(N)

#7
#sum of digits present in the string
def sumdigits(st):
    s=0
    for i in st:
        if i.isdigit()==True:
            x=int(i)
            s+=x
    print(s)
    if i.isdigit()==False:
        print('No digits are there in the string')
st=input('Enter the string: ')
sumdigits(st)

#8
#delete all occurances of char and create a new string
def deletechar(st,char):
    st1=''
    for i in st:
        if i!=char:
            st1+=i
    print(st1)
st=input('Enter the string: ')
char=input('Enter the character to delete: ')
deletechar(st,char)

#9
#recursion to find factorial
def fact(N):
    if N==0:
        return 1
    else:
        return N*fact(N-1)
N=int(input('Enter the no.: '))
print('Factorial: ',fact(N))

#10
#recursion to find sum of N no.s
def sumofdigit(N):
    if N==0:
        return 0
    else:
        return (N%10)+sumofdigit(N//10)
N=int(input('Enter the no.: '))
print('Sum: ',sumofdigit(N))

#11
#area of regular polygon using math module
from math import tan as t,pi as p,pow as o
n=int(input('Enter the no. of sides of regular polygon: '))
l=int(input('Enter the length of side: '))
area=n*(o(l,2)/(4*t(p/n)))
print('Area of regular polygon: ',area)

#12
#game of generating a no.
ch='y'
while ch=='Y' or ch=='y':
    import random
    p=random.randint(2,19)
    print('The no. guessed by the player: ',p)
    l=[]
    n=3
    for i in range(n):
        no=random.randint(101,199)
        l.append(no)
    print('The three no.s generated by the program: ',l)
    l1=[]
    for i in l:
        s=0
        for j in str(i):
            s+=int(j)
        l1.append(s)
    print('Sum: ',l1)   
    if p in l1:
        print('The player is a winner')
    else:
        print('The player is not a winner')
    ch=input('Does the player wish to continue?')

#13
#sum of sin(x) series
from math import pow as p,pi as i,factorial as f
def sin(x,n):
    s=0
    for j in range(n):
        sn=p(-1,j)
        y=x*(i/180)
        s+=((p(y,2.0*j+1))/f(2*j+1))*sn
    return s
x=int(input('Enter the value of x: '))
n=int(input('Enter the value of n: '))
print('Sum of sin(x) series: ',round(sin(x,n),2))
      

#14
#Listreverse,listcal,listinterchange
def listreverse(l):
    l1=[]
    for i in l:
        l1.insert(0,i)
    return l1
def listcal(l):
    s=0
    avg=0
    for i in l:
        s+=i
        avg=s/n
    return s,avg
def listinterchange(l):
    if n%2==0:
        i,j=0,n//2
    else:
        i,j=0,(n+1)//2
    while j<n:
        l[i],l[j]=l[j],l[i]
        i+=1
        j+=1
    return l
l=[]
n=int(input('Enter the limit: '))
for i in range(n):
    no=int(input('Enter the no.: '))
    l.append(no)
print('Original list: ',l)
print('1.Reverse\n2.Sum and Average\n3.Interchange')
while True:
    ch=int(input('Enter your choice: '))
    if ch==1:
        print('Reversed list: ',listreverse(l))
    elif ch==2:
        print('Sum: ',listcal(l)[0],'Average: ',listcal(l)[1])
    elif ch==3:
        print('Interchanged list: ',listinterchange(l))
    else:
        break
'''
#15
#dice roll game
import random
player1=input('Enter the name of player 1: ')
player2=input('Enter the name of player 2: ')
s1=0
s2=0
roll="y"
while roll=='Y' or roll=='y':
    print('Rolling the dices...')
    print('The values are....')
    p1=random.randint(1,6)
    print('The rolled value for player 1: ',p1)
    s1+=p1
    print('Sum of the values for player',player1,'is',s1)
    p2=random.randint(1,6)
    print('The rolled value for player 2: ',p2)
    s2+=p2
    print('Sum of the values for player',player2,'is',s2)
    if s1>=30 and (s2<30 or s2!=30):
        print('Player',player1,'is winner')
        break
    elif s2>=30 and (s1<30 or s1!=30):
        print('Player',player2,'is winner')
        break
    roll=input('Do you wish to roll the dices again?')

'''#13
#sum of sin(x) series
from math import pow as p
def fact(n):
    if n==1:
        return 1
    else:
        return n*fact(n-1)
def sin(x,n):
    s=0
    for i in range(n+1):
        s+=(p(-1,i)*p(x,2*i+1))/fact(2*i+1)
    return s
n=int(input('Enter the no. of terms: '))
x=int(input('Enter the value of x: '))
print(sin(x,n))'''


